version: '3.8'
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=music-system
    volumes:
      - db:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - backend

  api:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: ./server
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - backend
      - frontend
    volumes:
      - ./server:/server
volumes:
  db:
networks:
  backend:
  frontend:
